#!/usr/bin/env python3
"""Reconcile BetterVoting's BPML process sheet against this repo's BV case registry.

Three inventories track BetterVoting test coverage, and until now none of them knew
about the others:

  1. the **BPML sheet** (Drive) -- one row per L1/L2/L3 business process, with a
     "Test Case" column that sometimes names a BVxxx id;
  2. the **Test Cases sheet** (Drive) -- the manual QA log, one row per BVxxx with
     a pass/fail status;
  3. **bv_cases.csv** (this repo) -- every BV-backed election that exists as a
     runnable YAML case with a published answer key.

"Do we have coverage?" is a join across all three, and nobody had run it. This
script runs it and writes RECONCILIATION.md next to the snapshots.

The two Drive sheets cannot be read from CI, so they are committed here as dated
CSV **snapshots**. They are point-in-time copies, not a live feed -- the header of
the generated page says so, and re-snapshotting is a manual step.

    .venv/bin/python STARVote_LH_tabulation_engine/tools_adam/scripts/reconcile_bpml.py
"""
from __future__ import annotations

import csv
import re
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
BPML_DIR = REPO / "07_Concepts" / "tabulation_engines" / "BV" / "bpml"
REGISTRY = REPO / "07_Concepts" / "YAML_test_case_index" / "bv_cases.csv"
OUT = BPML_DIR / "RECONCILIATION.md"

SNAPSHOT_DATE = "2026-08-16"
ID_RE = re.compile(r"\bBV\d+[a-z]?(?:-r\d+)?\b", re.I)

# Cells that record a gap rather than a test id. Kept verbatim from the sheet.
GAP_MARKERS = {"missing", "missing document", "missing functionality",
               "missing functionality?"}


def _rows(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8-sig") as fh:
        return list(csv.DictReader(fh))


def _norm(tid: str) -> str:
    """BV0015 / bv15 / BV15 all key the same. Suffixes (-r2, a) are significant."""
    m = re.match(r"(?i)^bv0*(\d+)(.*)$", tid.strip())
    return f"BV{m.group(1)}{m.group(2).lower()}" if m else tid.strip().upper()


def main() -> int:
    bpml = _rows(BPML_DIR / "bpml_snapshot.csv")
    drive = _rows(BPML_DIR / "bv_testcases_snapshot.csv")
    repo = _rows(REGISTRY)

    drive_ids = {_norm(r["TestID"]) for r in drive if r["TestID"].strip()}
    repo_ids = {_norm(r["TestID"]) for r in repo if r.get("TestID", "").strip()}

    # --- BPML side -------------------------------------------------------
    cited: dict[str, list[str]] = {}
    gap_rows, doc_rows = [], 0
    for r in bpml:
        cell = (r["test_case_cell"] or "").strip()
        if r["doc_cell"].strip() and r["doc_cell"].strip() not in GAP_MARKERS:
            doc_rows += 1
        if cell.lower() in GAP_MARKERS:
            gap_rows.append(r)
            continue
        for tid in (_norm(m) for m in ID_RE.findall(cell)):
            cited.setdefault(tid, []).append(r["L3_process"])

    cited_ids = set(cited)
    in_repo = cited_ids & repo_ids
    in_drive_only = (cited_ids & drive_ids) - repo_ids
    nowhere = cited_ids - repo_ids - drive_ids

    # --- the other direction ---------------------------------------------
    repo_unreferenced = repo_ids - cited_ids
    drive_not_in_repo = drive_ids - repo_ids
    repo_not_in_drive = repo_ids - drive_ids

    by_l1 = Counter(r["L1"] for r in bpml)
    untested = [r for r in bpml
                if not (r["test_case_cell"] or "").strip()]

    def pct(n, d):
        return f"{100.0 * n / d:.0f}%" if d else "n/a"

    L = []
    a = L.append
    a("# BPML ↔ library reconciliation")
    a("")
    a("**Level: reference · deep dive**")
    a("")
    a(f"Generated by [`reconcile_bpml.py`](../../../../STARVote_LH_tabulation_engine/tools_adam/scripts/reconcile_bpml.py) "
      f"from committed snapshots of the two Drive sheets taken **{SNAPSHOT_DATE}**, "
      "joined against the live registry. The snapshots are point-in-time copies, not a live "
      "feed — re-snapshot before trusting a number that matters.")
    a("")
    a("## The headline")
    a("")
    a("| | |")
    a("|---|---:|")
    a(f"| BPML process rows | {len(bpml)} |")
    a(f"| …citing a test id | {sum(len(v) for v in cited.values())} |")
    a(f"| …recording a gap (`missing…`) | {len(gap_rows)} |")
    a(f"| …with **no test reference at all** | {len(untested)} ({pct(len(untested), len(bpml))}) |")
    a(f"| Distinct test ids cited by BPML | {len(cited_ids)} |")
    a(f"| …that exist as a runnable case in this repo | **{len(in_repo)}** |")
    a(f"| …that exist only in the Drive test sheet | {len(in_drive_only)} |")
    a(f"| …that exist in neither | {len(nowhere)} |")
    a("")
    a("| | |")
    a("|---|---:|")
    a(f"| Case rows in the library registry | {len(repo)} |")
    a(f"| …distinct BV elections behind them | {len(repo_ids)} |")
    a(f"| …referenced by any BPML row | {len(repo_ids & cited_ids)} |")
    a(f"| …**referenced by nothing in the sheet** | {len(repo_unreferenced)} ({pct(len(repo_unreferenced), len(repo_ids))}) |")
    a("")
    a(f"(The registry holds {len(repo)} rows but {len(repo_ids)} distinct ids: a multirace "
      "election backs several cases that all carry its one test id.)")
    a("")
    a("## What the numbers mean")
    a("")
    a(f"The sheet's coverage column is **{pct(len(untested), len(bpml))} empty** — which is honest, "
      "not a failure: it was built as a backlog. The problem is the other direction. The library "
      f"holds {len(repo)} runnable BV-backed case rows ({len(repo_ids)} distinct elections) and the sheet references "
      f"{len(repo_ids & cited_ids)} of them, so **{pct(len(repo_unreferenced), len(repo_ids))} of the "
      "testing work this project has already done is invisible to the document that is supposed to "
      "track testing coverage**.")
    a("")
    a("The two inventories also barely overlap by construction:")
    a("")
    a(f"- Drive test-sheet ids not in the library: **{len(drive_not_in_repo)}**")
    a(f"- Library cases not in the Drive test sheet: **{len(repo_not_in_drive)}**")
    a("")
    a("The Drive sheet is the older manual-QA range and stops in the low hundreds; the library's "
      "ids run to BV2284. They are not two views of one inventory — they are two inventories.")
    a("")

    if in_repo:
        a("## BPML rows that DO have a runnable case")
        a("")
        a("| Test id | BPML process | Library case |")
        a("|---|---|---|")
        idx = {_norm(r["TestID"]): r for r in repo if r.get("TestID")}
        for tid in sorted(in_repo, key=lambda s: int(re.sub(r"\D", "", s) or 0)):
            row = idx.get(tid, {})
            case = row.get("Case", "") or "—"
            for proc in cited[tid]:
                a(f"| `{tid}` | {proc} | {case} |")
        a("")

    if in_drive_only or nowhere:
        a("## BPML rows citing a test id with no runnable case")
        a("")
        a("These are the sheet's real coverage gaps — a process it believes is tested, "
          "where nothing in the library reproduces it.")
        a("")
        a("| Test id | BPML process | Where it exists |")
        a("|---|---|---|")
        for tid in sorted(in_drive_only | nowhere,
                          key=lambda s: int(re.sub(r"\D", "", s) or 0)):
            where = "Drive test sheet only" if tid in in_drive_only else "**nowhere**"
            for proc in cited[tid]:
                a(f"| `{tid}` | {proc} | {where} |")
        a("")

    if gap_rows:
        a("## Rows the sheet already flags as gaps")
        a("")
        a("The sheet doing its job — these cells are the most useful thing in it.")
        a("")
        a("| BPML process | Marker |")
        a("|---|---|")
        for r in gap_rows:
            a(f"| {r['L3_process']} | `{r['test_case_cell']}` |")
        a("")

    a("## Process rows by area")
    a("")
    a("| L1 area | rows |")
    a("|---|---:|")
    for k, v in sorted(by_l1.items(), key=lambda kv: (-kv[1], kv[0])):
        a(f"| {k} | {v} |")
    a("")
    a("---")
    a("")
    a("Related: [the docs information architecture](../bv_docs_information_architecture.md) · "
      "[BV registry](../../../YAML_test_case_index/BV_registry.md) · "
      "[all cases by method](../../../YAML_test_case_index/README.md)")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"reconcile_bpml: {len(bpml)} process rows, {len(repo_ids)} registry cases")
    print(f"  cited ids: {len(cited_ids)}  in repo: {len(in_repo)}  "
          f"drive-only: {len(in_drive_only)}  nowhere: {len(nowhere)}")
    print(f"  registry cases referenced by no BPML row: {len(repo_unreferenced)}")
    print(f"  wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
