#!/usr/bin/env python3
"""Report table columns that link SOME of their rows but not others.

The house overlinking rule (CLAUDE.md) says: *in a parallel list, link all or
none* — when a table column names several like things side by side (STAR ·
RCV-IRV · Ranked Robin · Plurality), linking only some of them reads as
arbitrary even when each individual choice was defensible.

That is the one linking rule with no machine gate, because the failure mode is
*partial* linking rather than a broken link: `check_links` sees nothing wrong,
the site builds, and only a human reading the rendered page notices. This
script does the counting half of that job — it finds columns where 0 < linked <
total and prints them. **It is advisory, not a gate**: whether a flagged column
is a genuine parallel list (methods, rules, candidates — fix it) or a
heterogeneous set of row labels (a comparison table whose leftmost column holds
questions like "Uses your lower ranks?" — leave it) is a judgment call the
script cannot make. Nothing here runs in the pre-commit hook.

    python STARVote_LH_tabulation_engine/tools_adam/scripts/report_partial_link_columns.py [--all-columns]

Generated pages are skipped: their links come from a builder, so a partial
column there is a generator question, not an editing slip.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
SKIP_PATH_PARTS = ("cases_pages/", "_tabulated", "site/", "node_modules/")
GENERATED_MARKERS = ("do not edit by hand", "auto-generated", "generated by")
LINK = re.compile(r"\[[^\]]+\]\([^)]+\)")
SEPARATOR = re.compile(r"^\s*\|[\s:|-]+\|\s*$")
MIN_ROWS = 3


def cells(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def scan(text: str, column: int) -> list[tuple[int, int, int]]:
    """Return (table start line, linked rows, total rows) for partial columns."""
    out: list[tuple[int, int, int]] = []
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        is_header = lines[i].lstrip().startswith("|") and i + 1 < len(lines) and SEPARATOR.match(lines[i + 1])
        if not is_header:
            i += 1
            continue
        start = i
        i += 2
        body: list[str] = []
        while i < len(lines) and lines[i].lstrip().startswith("|"):
            row = cells(lines[i])
            if len(row) > column:
                body.append(row[column])
            i += 1
        if len(body) >= MIN_ROWS:
            linked = sum(1 for c in body if LINK.search(c))
            if 0 < linked < len(body):
                out.append((start + 1, linked, len(body)))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--all-columns", action="store_true", help="check every column, not just the first")
    args = ap.parse_args()

    listed = subprocess.run(
        ["git", "ls-files", "*.md"], cwd=REPO_ROOT, capture_output=True, text=True, check=True
    ).stdout.split()

    findings: list[tuple[str, int, int, int, int]] = []
    for rel in listed:
        if any(part in rel for part in SKIP_PATH_PARTS):
            continue
        text = (REPO_ROOT / rel).read_text(errors="ignore")
        head = text[:1500].lower()
        if any(marker in head for marker in GENERATED_MARKERS):
            continue
        widest = max((len(cells(l)) for l in text.split("\n") if l.lstrip().startswith("|")), default=1)
        columns = range(widest) if args.all_columns else [0]
        for col in columns:
            for line, linked, total in scan(text, col):
                findings.append((rel, line, col, linked, total))

    for rel, line, col, linked, total in sorted(findings, key=lambda f: (f[4] - f[3]) / f[4], reverse=True):
        where = f"column {col + 1}" if args.all_columns else "first column"
        print(f"{rel}:{line}  {linked}/{total} {where} cells linked")
    print(f"\n{len(findings)} partially-linked columns in {len({f[0] for f in findings})} files (advisory — judge each one).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
